/*
- EXPRESSION TYPES
- BINARY OPERATORS
- NULL(COALESCING, CONDITIONAL)
- STATEMENT / STATEMENT BLOCKS
- SELECTION (IF, SWITCH)
- ITERATION WHILE, FOR, FOREACH)
- JUMP STATEMENTS
*/
/*
- EXPRESSION
- EQUALITY OPERATORS
- COMPARISON OPERATOR
- EQUALITY AND REF. TYPE
- CONDITIONAL OPERATOR
- SHORT CIRCUIT BR VS &
- TERNARY OPERATOR
*/
var total = 900; var vipThreshold = 1000; 
var isVip =  total >= vipThreshold ? true : false; 
var discount = total >= vipThreshold? 0.05m: 0.0m;